### ISSUE TITLE
Account for nullable reference types when generating schemas

### ISSUE THREAD

**Issue by dstelljes** [ch-robinson/dotnet-avro#102]
At present, the type resolvers take an all-or-nothing approach to determining nullability of reference types. The schema generator would be more useful if the resolvers took [nullable reference type metadata](https://github.com/dotnet/roslyn/blob/master/docs/features/nullable-metadata.md) into account.

This would be a breaking change given that it’s incongruent to the existing `resolveReferenceTypesAsNullable` option on the `TypeResolver`. One possible implementation:

* Remove the `resolveReferenceTypesAsNullable` boolean and introduce a `NullableReferenceTypeBehavior` enum (like `TemporalBehavior`, `TombstoneBehavior`, etc.).
  * `None` (never generate nullable union schemas; equivalent to `resolveReferenceTypesAsNullable: false`)
  * `Semantic` (always generate nullable union schemas; equivalent to `resolveReferenceTypesAsNullable: true`)
  * `FromMetadata` (look for nullable metadata, falling back to `None` behavior if oblivious)
* Make `FromMetadata` the default behavior. This matches the current default behavior (`resolveReferenceTypesAsNullable: false`) for oblivious types and transparently enables better behavior for non-oblivious types.
* Keep the default behavior of `dotnet avro generate` as long as nullable reference types are opt-in, but add a flag to support generating non-oblivious code.

Open questions:

* What’s the safest way to reflect on `NullableAttribute`/`NullableContextAttribute`? Direct use of those types isn’t allowed in source, but it’s still possible to grab them by name:
    ```csharp
    var attribute = Type.CustomAttributes.SingleOrDefault(attribute => attribute.FullName == "...");
    ```
* For consistency, should we also enum-ify `resolveUnderlyingEnumTypes`?

**Comment by Jeff-McIntosh** [comment]
@dstelljes, this functionality would be useful for the documents team. Is this still on track for the 8.0.0 milestone? Until this gets in, we'll be running **dotnet avro** and then hand-editing the output any time we need to update our schema.

**Comment by dstelljes** [comment]
Yeah, it will be included in 8.0.0; we’re hoping to finally get it out the door early Q4.

**Comment by teemka** [comment]
Hi,

I implemented schema support for **Nullable Reference Types** in records in a project and I wanted to share my code. You can see it here:
https://gist.github.com/teemka/4c77ed9cce130c9df4b92c436583d693

Keep in mind that this implementation is missing support for arrays with nullable types in them.

**Comment by dstelljes** [comment]
Thanks for sharing! As I understand it, checking the top-level record isn’t actually possible; `.BuildSchema<Record>()` and `.BuildSchema<Record?>` are indistinguishable.
