### ISSUE TITLE
DateTime conversion failed while consuming Message

### ISSUE THREAD

**Issue by mastery-ravi-jaiswal** [ch-robinson/dotnet-avro#109]
While consuming message using Chr.avro (Message produce by Apache.avro) facing issue for DateTime field "**No coercion operator is defined between types 'System.Int64' and 'System.Nullable`1[System.DateTime]**'."

Note:  Apache Avro schema which is used for produce message
{
	"type": "record",
	"name": "ABC",
	"namespace": "kafka",
	"fields": [{
			"name": "name",
			"type": ["null", "string"]
		}, {
			"name": "code",
			"type": ["null", "string"]
		},
		{
			"name": "cancel_date",
			"default": null,
			"type": ["null", {
				"type": "int",
				"logicalType": "date"
			}]
		}
	]
}

POCO Class to consume message(Chr.avro) which is produce message(apache.avro) by above schema:
public class ABC
	{
		
		public string Name;
		public string Code;
		public DateTime? CancelDate;
	}

**Comment by dstelljes** [comment]
Chr.Avro doesn’t map the `"date"` logical type to `DateTime` because there’s no time component. If you want to map to a `DateTime`, use `"timestamp-millis"` or `"timestamp-micros"`. For more details, see the documentation: https://engineering.chrobinson.com/dotnet-avro/internals/mapping#dates-and-times

**Comment by mastery-amol-wanjare** [comment]
@dstelljes - Is there any workaround to this issue, we are also facing some other issues with the Apache Avro library while consuming the Kafka message so we are planning to use this Dotnet Avro library for consuming the message. But as the Producer is developed by another team we do not have control over what datatype they use for DateTime. Currently, they are using "date" type while producing the message and we would like to use the Dotnet Avro to consume the same message. Is there any workaround?

**Comment by dstelljes** [comment]
You have a couple of options. First, you could change the `CancelDate` field type to an `int` and handle any arithmetic in your application code. Second, you could add a custom deserialization case:

```csharp
var codec = new BinaryCodec();
var resolver = new ReflectionResolver();

var deserializer = new BinaryDeserializerBuilder(BinaryDeserializerBuilder.CreateBinaryDeserializerCaseBuilders(codec)
        .Prepend(builder => new DateDeserializerBuilderCase (codec)))
        .BuildDeserializer<ABC>(schema);
```

```csharp
public class DateDeserializerBuilderCase : BinaryDeserializerBuilderCase
{
    public IBinaryCodec Codec { get; }

    public TimestampDeserializerBuilderCase(IBinaryCodec codec)
    {
        Codec = codec ?? throw new ArgumentNullException(nameof(codec), "Binary codec cannot be null.");
    }

    public override IBinaryDeserializerBuildResult BuildExpression(TypeResolution resolution, Schema schema, IBinaryDeserializerBuilderContext context)
    {
        var result = new BinaryDeserializerBuildResult();

        if (schema.LogicalType is DateLogicalType)
        {
            if (resolution is TimestampResolution)
            {
                if (!(schema is IntSchema))
                {
                    throw new UnsupportedSchemaException(schema);
                }

                Expression epoch = Expression.Constant(new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc));
                Expression expression = Codec.ReadInteger(context.Stream);

                var addDays = typeof(DateTime)
                    .GetMethod(nameof(DateTime.AddDays));

                result.Expression = GenerateConversion(
                    Expression.Call(epoch, addDays, Expression.ConvertChecked(expression, typeof(double))),
                    resolution.Type
                );
            }
            else
            {
                result.Exceptions.Add(new UnsupportedTypeException(resolution.Type));
            }
        }
        else
        {
            result.Exceptions.Add(new UnsupportedSchemaException(schema));
        }

        return result;
    }
}
```

**Comment by mastery-ravi-jaiswal** [comment]
@dstelljes  I tried with IntSchema and RecordSchema with logical type DateLogicType but facing issue  of "InvalidOperationException: No coercion operator is defined between types 'System.DateTime' and 'ABC'".
What we need to pass for the schema field?

 Chr.Avro.Abstract.Schema schema = new Chr.Avro.Abstract.IntSchema
            {
                LogicalType = new DateLogicalType()
            };
or 
  RecordField r = new RecordField("cancel_date", new IntSchema
            {
                LogicalType = new DateLogicalType()
            }
            );

            Chr.Avro.Abstract.Schema schema = new Chr.Avro.Abstract.RecordSchema("cancel_date", new RecordField[] { r })
            {
                LogicalType = new DateLogicalType(),
                Namespace = "ABC",
            };

**Comment by dstelljes** [comment]
If you have a schema in JSON already (like the one @mastery-ravi-jaiswal posted initially), use the schema reader instead of constructing it manually:

```csharp
var json = "{\"type\":\"record\",...}";
var schema = new JsonSchemaReader().Read(json);
```

That's equivalent to writing:

```csharp
var schema = new RecordSchema("ABC", new[]
{
    // other fields omitted

    new RecordField("cancel_date", new IntSchema
    {
        LogicalType = new DateLogicalType()
    })
});
```

**Comment by mastery-amol-wanjare** [comment]
@dstelljes - Thank you for the quick response. I have two more questions based on your response.

1. How do we associate the deserializer that we created with the Kafka consumer?
2. As we have other datatype fields also in the schema, What modifications should we do in the Deserializer to handle the default datatypes mappings? For fields like String, Int, UUID, etc. 

 Below is the code snippet -

---Program.cs code-----------------------------

 var schema = new JsonSchemaReader().Read(@"{""type"":""record"",""name"":""NewEvent"",""namespace"":""TestChrAvro"",""fields"":[{""name"":""id"",""type"":""string""},{""name"":""sequence"",""type"":""int""},{""name"":""testid"",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""available_start_date"",""default"":null,""type"":[""null"",{""type"":""int"",""logicalType"":""date""}]}]}");
            var codec = new BinaryCodec();
            var resolver = new ReflectionResolver();
            var deserializer = new BinaryDeserializerBuilder(BinaryDeserializerBuilder.CreateBinaryDeserializerCaseBuilders(codec)
                                .Prepend(builder => new DateDeserializerBuilderCase(codec))
                                //.Prepend(builder => new IntegerDeserializerBuilderCase(codec))
                                //.Prepend(builder => new StringDeserializerBuilderCase(codec))                                
                                )
                                .BuildDeserializer<NewEvent>(schema);


            using (var registry = new CachedSchemaRegistryClient(schemaRegistryConfig))
            {
                var builder = new ConsumerBuilder<string, NewEvent>(consumerConfig)
                    .SetAvroValueDeserializer(registry)  //TODO : How to assign custom deserializer
                    .SetErrorHandler((_, error) => Console.Error.WriteLine(error.ToString()));

                using (var consumer = builder.Build())
                {
                    consumer.Subscribe(topicName);
                    while (true)
                    {
                        try
                        {
                            var result = consumer.Consume();
                            Console.WriteLine(result.Value);
                        }
                        catch (Exception ex)
                        {
                            Console.WriteLine(ex);
                        }
                    }
                }
            }


------------------DateDeserializerBuilderCase code-------------------------------------
    public override IBinaryDeserializerBuildResult BuildExpression(TypeResolution resolution, Schema schema, IBinaryDeserializerBuilderContext context)
        {
            var result = new BinaryDeserializerBuildResult();

            
            if (schema.LogicalType is DateLogicalType)
            {
                if (resolution is IntegerResolution || resolution is TimestampResolution)
                {
                    if (!(schema is IntSchema))
                    {
                        throw new UnsupportedSchemaException(schema);
                    }

                    Expression epoch = Expression.Constant((DateTime?)new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc));
                    Expression expression = Codec.ReadInteger(context.Stream);

                    var addDays = typeof(DateTime)
                        .GetMethod(nameof(DateTime.AddDays));
                    
                    result.Expression = GenerateConversion(Expression.Call(epoch, addDays, Expression.ConvertChecked(expression, typeof(double))), resolution.Type);
                }
                else
                {
                   // return base.BuildExpression(resolution,schema,context);
                    result.Exceptions.Add(new UnsupportedTypeException(resolution.Type));
                }
            }
            else
            {
                result.Exceptions.Add(new UnsupportedSchemaException(schema));
            }
            // base.BuildExpression(resolution, schema, context);
            return result;
        }


------Schema file-------------------------
{
  "type": "record",
  "name": "NewEvent",
  "namespace": "TestChrAvro",
  "fields": [
    {
      "name": "id",
      "type": "string"
    },
    {
      "name": "sequence",
      "type": "int"
    },
    {
      "name": "testid",
      "type": {
        "type": "string",
        "logicalType": "uuid"
      }
    },
    {
      "name": "available_start_date",
      "default": null,
      "type": [
        "null",
        {
          "type": "int",
          "logicalType": "date"
        }
      ]
    }
  ]
}


------------------------NewEvent class-----------------------------------------
 public class NewEvent
    {
        public int sequence { get; set; }

        public string id { get; set; }

        public string testid { get; set; }

	public DateTime? available_start_date { get; set; }

    }

**Comment by dstelljes** [comment]
1.  Are you using a Schema Registry? If so, use it to deserialize instead of embedding the schema in your application:

    ```csharp
    var codec = new BinaryCodec();
    var resolver = new ReflectionResolver();

    var deserializerBuilder = new BinaryDeserializerBuilder(BinaryDeserializerBuilder.CreateBinaryDeserializerCaseBuilders(codec)
        .Prepend(builder => new DateDeserializerBuilderCase(codec)));

    using (var registry = new CachedSchemaRegistryClient(schemaRegistryConfig));
    {
        var consumerBuilder = new ConsumerBuilder<string, NewEvent>(consumerConfig)
            .SetValueDeserializer(new AsyncSchemaRegistryDeserializer(registry, deserializerBuilder));

        using (var consumer = consumerBuilder.Build())
        {
            // ...
        }
    }
    ```

    If not, implement Confluent.Kafka’s deserializer interface and use that:

    ```csharp
    var consumerBuilder = new ConsumerBuilder<string, NewEvent>(consumerConfig)
        .SetValueDeserializer(new AvroDeserializer<NewEvent>(schema));

    using (var consumer = consumerBuilder.Build())
    {
        // ...
    }
    ```

    ```csharp
    public class AvroDeserializer<T> : Confluent.Kafka.IDeserializer<T>
    {
        private readonly IBinaryDeserializer<T> _deserializer;

        public AvroDeserializer(Schema schema)
        {
            var codec = new BinaryCodec();
            var resolver = new ReflectionResolver();

            _deserializer = new BinaryDeserializerBuilder(BinaryDeserializerBuilder.CreateBinaryDeserializerCaseBuilders(codec)
                .Prepend(builder => new DateDeserializerBuilderCase(codec)))
                .BuildDeserializer(schema);
        }

        T Deserialize(ReadOnlySpan<byte> data, bool isNull, SerializationContext context)
        {
            return isNull ? null : _deserializer.Deserialize(data.ToArray());
        }
    }
    ```

2.  You shouldn’t need to customize the deserializer builder any further; `"date"` is the only logical type you’re using that isn’t supported.

**Comment by mastery-ravi-jaiswal** [comment]
@dstelljes we tried the approach of deserializer as you shared but while consuming message we are getting default values for 2nd approach.
For First approach getting error **SetValueDeserializer(new AsyncSchemaRegistryDeserializer(registry, deserializerBuilder))** 
It requires Confulent.Kafka.IDeserializer while try to cast its giving exception
I attached my code. Can you once look into it.

[TestChrAvro.zip](https://github.com/ch-robinson/dotnet-avro/files/5688790/TestChrAvro.zip)

**Comment by mastery-amol-wanjare** [comment]
@dstelljes I am also getting typecast error on SetValueDeserializer(new AsyncSchemaRegistryDeserializer(registry, deserializerBuilder)) as it needs Confulent.Kafka.IDeserializer. Any suggestion?

**Comment by dstelljes** [comment]
Okay, since you’re using the Schema Registry in your producer, you should disregard the second approach. To get the first approach to work, I think you just need to add [`.AsSyncOverAsync()`](https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/SyncOverAsyncSerializer.cs#L89) (my fault for not trying to compile the earlier example):

```csharp
var consumerBuilder = new ConsumerBuilder<string, NewEvent>(consumerConfig)
    .SetValueDeserializer(new AsyncSchemaRegistryDeserializer(registry, deserializerBuilder).AsSyncOverAsync());
```

**Comment by mastery-amol-wanjare** [comment]
Thank you so much @dstelljes, Looks like it is working. Thanks again.
