### ISSUE TITLE
The serialization is very slow 

### ISSUE THREAD

**Issue by sergiutugulschi** [ch-robinson/dotnet-avro#110]
If trying to serialize 10 000 records of a custom object, it takes 1.3 minute to complete 
in comparison Json serializer takes 1.3 seconds.

Used code for serialization: 
var serializer = new BinarySerializerBuilder().BuildSerializer<T>(AvroSchemas.Schemas[schema]);
var data = serializer.Serialize(message); 

AvroSchemas contains a dictionary with preloaded JsonSchemaReader.

**Comment by dstelljes** [comment]
Instead of building a new serializer for each message, use one serializer instance per schema. Building a new serializer for each message is likely what’s slowing you down.

**Comment by sergiutugulschi** [comment]
Thank you, now working almost as JsonSerializer.
