### ISSUE TITLE
Invalid record alias; a definition for XYZ.ABC was already read.

### ISSUE THREAD

**Issue by mastery-ravi-jaiswal** [ch-robinson/dotnet-avro#111]
@dstelljes  While consuming message using Chr.avro (Message produce by Apache.avro) facing issue for  Aliases Consume:System.IO.InvalidDataException: Invalid record alias; a definition for XYZ.ABC was already read.

```
{
	"type": "record",
	"name": "ABC",
	"namespace": "XYZ",
	aliases":["XYZ.ABC"]
	"fields": [{
			"name": "name",
			"type": ["null", "string"]
		}, {
			"name": "code",
			"type": ["null", "string"]
		},
		{
			"name": "cancel_date",
			"default": null,
			"type": ["null", {
				"type": "int",
				"logicalType": "date"
			}]
		}
	]
}
```
Same schema works fine after remove **aliases**. But In our case we require **aliases** 
Can you suggest any workaround this?

**Comment by dstelljes** [comment]
In your example, the `XYZ.ABC` alias is equal to the qualified record name, and that’s causing the conflict. Can you explain why you need the alias?

**Comment by mastery-ravi-jaiswal** [comment]
We already produce(Apache.Avro) message for above mention schema which contains "alias" . Now we want to consume messages using Chr.Avro.

**Comment by mastery-amol-wanjare** [comment]
@dstelljes  - In our scenario, Producer code is developed by some other team and we are working on the consumer piece. We do not have access to the Producer code. We have access to Schema file to generate the classes for Consumer application.

**Comment by dstelljes** [comment]
This will be resolved with 7.0.3.

**Comment by mastery-amol-wanjare** [comment]
@dstelljes  - Do you know when will version 7.0.3 be out?

**Comment by dstelljes** [comment]
It’s been uploaded to NuGet; you should see it soon if you don’t already.
