### ISSUE TITLE
Logical Type Decimal WithOut Scale

### ISSUE THREAD

**Issue by mastery-ravi-jaiswal** [ch-robinson/dotnet-avro#115]
@dstelljes We have a field have logical type is decimal while consuming message using Chr.Avro getting the issue of Scale is require for logical type decimal

We already produce(Apache.Avro) message for below mention schema which have logical type decimal without scale  . Now we want to consume messages using Chr.Avro.
Can you suggest any workaround this?

```
{
	"type": "record",
	"name": "ABC",
	"namespace": "ABC",
	aliases":["ABC"]
	"fields": [{
			"name": "name",
			"type": ["null", "string"]
		}, {
			"name": "code",
			"type": ["null", "string"]
		},
		{
								"name": "amount",
								"type": {
									"type": "bytes",
									"logicalType": "decimal",
									"precision": 28
								}
								},
		{
			"name": "cancel_date",
			"default": null,
			"type": ["null", {
				"type": "int",
				"logicalType": "date"
			}]
		}
	]
}
```

**Comment by dstelljes** [comment]
Thanks for the report; it looks like we don’t properly implement the spec in this case. We’ll release a fix with 7.0.4 shortly.
