### ISSUE TITLE
Binary serializer can write out-of-range values for int schemas

### ISSUE THREAD

**Issue by dstelljes** [ch-robinson/dotnet-avro#120]
[This test](https://github.com/ch-robinson/dotnet-avro/blob/7.0.4/tests/Chr.Avro.Binary.Tests/IntegerSerializationTests.cs#L143) should not pass; values outside of the Int32 range should not be able to be written for int schemas.

**Comment by the-chieftain** [comment]
Is the expected behaviour to throw from when calling the BuildSerializer and BuildDeserializer functions?

Or only when attempting to write or read values outside of the 32-bit range?

I have it currently throwing "Chr.Avro.UnsupportedSchemaException: IntSchema only supports 32-bit integer types."

**Comment by dstelljes** [comment]
The expected behavior is to throw when writing. I’m not sure about reading; the Java library implements int/long reads separately and would throw `InvalidNumberEncodingException` (https://github.com/apache/avro/blob/release-1.10.2/lang/java/avro/src/main/java/org/apache/avro/io/BinaryDecoder.java#L172), so we should probably throw there as well.

You should be able to build a serializer/deserializer that maps `IntSchema` to any numeric type: https://github.com/ch-robinson/dotnet-avro/blob/7.x/src/Chr.Avro.Binary/BinarySerializerBuilder.cs#L1223

**Comment by dstelljes** [comment]
Released with 8.0.0-pre.1.
