### ISSUE TITLE
ArgumentNullException while producing Message using Chr.Avro

### ISSUE THREAD

**Issue by mastery-aparna-kamble** [ch-robinson/dotnet-avro#122]
While producing message using Chr.avro, object Address is not setting to null or any of the field of Address is not setting to null and the same for Contact.
**Exception : Error producing message: Confluent.Kafka.ProduceException`2[System.String,test]: Local: Value serialization error
 ---> System.ArgumentNullException: String reference not set to an instance of a String. (Parameter 's')
   at System.Text.Encoding.GetBytes(String s)
   at Address serializer(Closure , Address )**
   
**Chr. Avro Class File:**
using System.Collections.Generic;
namespace test
{
    public class Address
    {
        public string name { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string country { get; set; }
        public string code { get; set; }
    }

    public class Contact
    {
        public string name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
    }

    public class TestMessage
    {
        public string name { get; set; }
        public Address billaddress { get; set; }
        public Contact contact { get; set; }
        public string paymentmethod { get; set; }
    }
}

**Producer :** 
		string bootstrapServers = "localhost:9092";
                string schemaRegistryUrl = "http://localhost:8082";
                string topicName = "message";
                var producerConfig = new ProducerConfig
                {
                    BootstrapServers = bootstrapServers
                };
                var avroSerializerConfig = new AvroSerializerConfig
                {
                    BufferBytes = 100
                };
                var schemaRegistryConfig = new SchemaRegistryConfig
                {
                    Url = schemaRegistryUrl,
                };
               

                using (var schemaRegistry = new CachedSchemaRegistryClient(schemaRegistryConfig))
                using (var producer =
                    new ProducerBuilder<string, TestMessage>(producerConfig)
                        .SetAvroKeySerializer(schemaRegistry, registerAutomatically: AutomaticRegistrationBehavior.Always)
                        .SetAvroValueSerializer(schemaRegistry, registerAutomatically: AutomaticRegistrationBehavior.Always)
                        .Build())

                {
                    string text;
                    while ((text = Console.ReadLine()) != "q")
                    {
                        TestMessage msg = new TestMessage();
			msg.name = null;
                        msg.billaddress = new Address()
                        {
                            name = "test",
                            address1 = "test",
			    address2 = null,                                  //Throwing error
                            city = "test",
                            state = "test",
                            zip = "12121234",
                            country = "test",
                            code = "test"
                        };
		        msg.contact = null;                                   //Throwing error
		        msg.paymentmethod = "test";

                        try
                        {
                            await producer
                            .ProduceAsync(topicName, new Message<string, TestMessage> { Key = text, Value = msg }).
                            ContinueWith(task =>
                            {
                                ...
                            });
                        }
                        catch (Exception ex)
                        {
                            Console.WriteLine(ex);
                        }
                    }
                }

**Comment by dstelljes** [comment]
When you use `registerAutomatically`, Chr.Avro will generate a schema that doesn’t allow non-null values unless you customize the resolver. See https://github.com/ch-robinson/dotnet-avro/discussions/88#discussioncomment-178550 for an example.

**Comment by mastery-aparna-kamble** [comment]
Thank you for your quick assistance.
