### ISSUE TITLE
Json data validation against avro schema

### ISSUE THREAD

**Issue by krishnan-unni** [ch-robinson/dotnet-avro#123]
This is more of a question since I couldn't find much documentation regarding json data validation.
Say I have a json data as below:

{
"firstname" : "Kris",
"lastname": "Wade"
}

This data is from an incoming stream. I have a corresponding avro schema in json in a file.
Is it possible to validate the data stream against the schema?

**Comment by dstelljes** [comment]
At the moment, this isn’t supported, but it will be in the next major release when we land #2.

**Comment by krishnan-unni** [comment]
Thanks @dstelljes , Is there a release ETA?

**Comment by dstelljes** [comment]
We’re aiming for 8.0.0 by the end of this month.

**Comment by krishnan-unni** [comment]
Thanks a lot.

**Comment by krishnan-unni** [comment]
@dstelljes is there a 8.0.0 ETA? I cant see any release for it yet. Or delayed?

**Comment by dstelljes** [comment]
It’s delayed. I don’t have a specific ETA, but it should be within the next week.
