### ISSUE TITLE
Unable to generate schema for type defined in .NET 5 assembly

### ISSUE THREAD

**Issue by mdrgeniebelt** [ch-robinson/dotnet-avro#127]
Hi,

I'm probably doing something stupid but I'm unable to generate avro schema using dotnet avro cli tool.

Command I'm executing:
`dotnet avro create -a bin/Debug/net5.0/Events.dll -t Events.AccountEvent`

And error I'm getting in response:
`The type could not be found. You may need to provide additional assemblies.`

So question is _what am I doing wrong here?_ 😞 Thanks in advance!

Here is decompiled assembly in ILSpy:
![Screenshot 2021-02-08 at 17 25 23](https://user-images.githubusercontent.com/44974903/107248502-a55a4e00-6a32-11eb-8eca-1080ab8dcdb3.png)

**Comment by dstelljes** [comment]
Which version of the CLI are you using (`dotnet avro --version`)? There was a bug fixed in 7.0.2 (https://github.com/ch-robinson/dotnet-avro/issues/99) that could cause this; just want to validate before digging further.

**Comment by mdrgeniebelt** [comment]
`Chr.Avro.Cli 7.0.4`

**Comment by dstelljes** [comment]
What happens if you change the target from `net5.0` to `netstandard2.0`? The CLI would have been compiled as a .NET 3.1 application; it could be that there’s a compatibility problem there.

**Comment by mdrgeniebelt** [comment]
Yeah seems like it was the issue, I ran it again and it generated schema correctly :) 

`{"name":"Events.AccountEvent","type":"record","fields":[{"name":"Email","type":"string"},{"name":"Id","type":{"type":"string","logicalType":"uuid"}}]}`

Any plans though to compile it against .net5.0? 

Thanks!

**Comment by dstelljes** [comment]
Yeah, the next major release will bump it to .NET 5. I’ll also keep this open as a bug since we’d want this to fail with a better message.

**Comment by dstelljes** [comment]
Thanks for your patience on this; the 7.1.0 release later today will add `net5.0` as a CLI target framework.
