### ISSUE TITLE
CLI doesn't work in .NET SDK 5.0

### ISSUE THREAD

**Issue by eshepelyuk** [ch-robinson/dotnet-avro#139]
Hello @dstelljes 

I am attaching sample project that reproduces the issue

1. Unpack [avro.net5.zip](https://github.com/ch-robinson/dotnet-avro/files/6468787/avro.net5.zip)
1. Try to build docker
    $ docker build -t chr/avro .
1. Build fails with [error.log](https://github.com/ch-robinson/dotnet-avro/files/6468768/error.log)

The issue is not specific to docker build or local tool installation
* it's reproduced while setting up CLI globally ( with `--global`)
* it's reproduced on local PC ( both global and local installation)

CLI doesn't work until one installs .NET SDK 3.x.

**Comment by dstelljes** [comment]
Thanks for the thorough report. This is related to #127, but I’ll keep this open so that we make sure to test this type of installation.

**Comment by dstelljes** [comment]
Thanks for your patience on this; the 7.1.0 release later today will add `net5.0` as a CLI target framework.
