### ISSUE TITLE
Support `nint` and `nuint` types

### ISSUE THREAD

**Issue by dstelljes** [ch-robinson/dotnet-avro#140]
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nint-nuint

**Comment by the-chieftain** [comment]
Does it make sense to support native integer types for storage? For example, if a 32-bit system serialises an 'nint' then what type does a 64-bit system deserialise it as?

**Comment by dstelljes** [comment]
Avro encodes all integers as variable-length, so the encoding would be identical. The library has always been pretty lax about [what types to map to integral schemas](https://engineering.chrobinson.com/dotnet-avro/internals/mapping/#numbers):

> Integers are [zig-zag encoded](https://avro.apache.org/docs/current/spec.html#binary_encoding), so they take up as much space as they need. For that reason, Chr.Avro imposes no constraints on which numeric types can be serialized or deserialized to `"int"` or `"long"`—if a conversion exists, the binary serializer and deserializer will use it.

**Comment by the-chieftain** [comment]
That makes sense.. I saw the open bug on serialising long values which ties it all together.

**Comment by dstelljes** [comment]
Released in 8.0.0-rc.0.
