### ISSUE TITLE
NuGet Package?

### ISSUE THREAD

**Issue by dannymyers** [ch-robinson/dotnet-avro#16]
This looks like an incredible well-written library. Do you have any plans to put this in NuGet?

**Comment by dstelljes** [comment]
Yep, all packages are available via NuGet:

https://www.nuget.org/packages/Chr.Avro
https://www.nuget.org/packages/Chr.Avro.Binary
https://www.nuget.org/packages/Chr.Avro.Cli
https://www.nuget.org/packages/Chr.Avro.Codegen
https://www.nuget.org/packages/Chr.Avro.Confluent
https://www.nuget.org/packages/Chr.Avro.Json

We link to the CLI and Confluent packages in the readme, but we could note more explicitly that the NuGet names match the assembly names, not the repo name.

**Comment by dannymyers** [comment]
Thanks for the response. I see it in NuGet today, but it wasn't showing up for me yesterday. Some weird glitch or type on my part. Excited to get working with this library.
