### ISSUE TITLE
Is it possible to generate class with Guid ?

### ISSUE THREAD

**Issue by ievgenii-shepeliuk** [ch-robinson/dotnet-avro#168]
Hello 

I am using `dotnet avro generate` to create C# class from Avro schema.
Since Avro supports `logicalType: "uuid"`  for string fields, it would be great to have a peroperty of ``Guid` type instead of `string` 

Is it possible to achieve now ? If yes - could you please explain.

If it's not possible - can this be a feature request for C# class generator ?

PS: is C# class generation CLI is extensible now at all, i.e. to reuse the same logic for schema to class generation and deserializaion from kafka to an instance ?

**Comment by ievgenii-shepeliuk** [comment]
> Thanks for the suggestion. We’ll cut a new 7.2.x in the next couple of days.
> 
> You can use the Chr.Avro.Codegen library directly in your applications. Presently Chr.Avro does not implement a source generator, which sounds like you’re after, but that’s something we could look at adding.

Thanks for fixing it.

But there's C# source generator - `dotnet avro generate` from `Chr.Avro.Cli`, what did you mean with 

> Presently Chr.Avro does not implement a source generator,

**Comment by dstelljes** [comment]
A [.NET source generator](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview), which would support using generated code transparently.
