### ISSUE TITLE
Nullable fields from schema are not reflected in generated C#

### ISSUE THREAD

**Issue by ievgenii-shepeliuk** [ch-robinson/dotnet-avro#169]
Hello

I'm using `dotnet avro generate` to create C# class from Avro schema.

My schema looks like 

```json
{
  "name": "Models.MyClass",
  "type": "record",
  "fields": [
    {"name": "BoolField", "type": ["null", "boolean"]},
    {"name": "StringField", "type": ["null", "string"]},
    {
      "name": "RecordField",
      "type": ["null", {
        "name": "Models.Credentials",
        "type": "record",
        "fields": [
          {"name": "Password", "type": "string"},
          {"name": "Username", "type": "string"}
        ]
      }]
    }, {
      "name": "EnumField",
      "type": ["null", {
        "name": "Models.AccountStatus",
        "type": "enum",
        "symbols": ["New", "Active"]
      }]
    }
  ]
}
```

I expect that properties `BoolField`, `StringField`, `RecordField`, `EnumField` will be nullable in generated class. But they are not.
The resulting C# class looks like 

```csharp
namespace Models
{
    public enum AccountStatus
    {
        New,
        Active
    }

    public class Credentials
    {
        public string Password { get; set; }
        public string Username { get; set; }
    }

    public class MyClass
    {
        public bool? BoolField { get; set; }
        public string StringField { get; set; }
        public Credentials RecordField { get; set; }
        public AccountStatus EnumField { get; set; }
    }
}
```

Am I missing smth or this is a bug in code generation ?

**Comment by dstelljes** [comment]
At the moment, code generation only supports nullable value types (note the `bool?` above), not reference types. We plan to fully support nullable reference types in 8.x.

That said, enums are value types and thus should be supported currently; #171 fixes that bug and will be included in the next 7.2.x.

**Comment by ievgenii-shepeliuk** [comment]
Looking forward new release, thanks for fixing it.

**Comment by ievgenii-shepeliuk** [comment]
@dstelljes is it possible to somehow hack it on serialization level, so even if fields is not nullable in C# class - when value of reference type is null - it will be serialized as `null` ?

**Comment by dstelljes** [comment]
Yes, that’s how Chr.Avro currently behaves—the library is oblivious to C# 8+ nullable reference types.

**Comment by ievgenii-shepeliuk** [comment]
Can you provide an example ?  I have an exception when serializing messages.

Although I have more complicated setup - i am wrapping Chr.Avro serializer to use it together with https://github.com/Farfetch/kafka-flow

I am creating an instance 
```
_serializer = new AsyncSchemaRegistrySerializer<T>(schemaRegistryClient);
```

and then invoke `SerializeAsync()`

**Comment by ievgenii-shepeliuk** [comment]
Yes, worked. Thanks for your help !
