### ISSUE TITLE
'Chr.Avro.Confluent Producer' generating error when the message has more than one properties with similar names separated only by a '_'

### ISSUE THREAD

**Issue by alanbassi** [ch-robinson/dotnet-avro#179]
Hi,

'Chr.Avro.Confluent Producer' generating error when the message has more than one properties with similar names separated only by a '_'

For example:

``` 
using (var schemaRegistry = new CachedSchemaRegistryClient(schemaRegistryConfig))
                using (var producer = new ProducerBuilder<string, MyMessage>(config)
                                            .SetAvroValueSerializer(schemaRegistry, registerAutomatically: AutomaticRegistrationBehavior.Always)
                                            .SetErrorHandler((_, error) => Console.Error.WriteLine(error.ToString()))
                                            .Build())
                {
                        var result = await producer.ProduceAsync(
                            "MY_TOPIC_AVRO",
                            new Message<string, MyMessage> { Key = "Test", Value = new MyMessage() { A1_COD_TEST = "Test", A1_CODTEST = "Test2" } });                    
                }
```

In the message as you can see the properties are 'A1_COD_TEST' and 'A1_CODTEST'. In other words, the only difference is the '_'. An object like this and C# might seem strange, but unfortunately this is the scenario I have.

When I try to produce this message the response I get is: 
```Confluent.Kafka.ProduceException '2
  HResult=0x80131500
  Message=Local: Value serialization error
  Source=Confluent.Kafka
  StackTrace:
   at Confluent.Kafka.Producer`2.<ProduceAsync>d__56.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ProducerKafka.Producer.<Run>d__0.MoveNext() in C:\Users\alan.lima\repos_git\ProducerKafka\Producer.cs:line 30

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
InvalidOperationException: Sequence contains more than one matching element'
```

The same does not occur when I put a different value at the end of one of these properties.

Could this be a producer bug?

**Comment by dstelljes** [comment]
This is actually intentional behavior, but the error message could be less cryptic. To support mapping multiple casing schemes to idiomatic .NET names, field names are compared inexactly. From [the docs](https://engineering.chrobinson.com/dotnet-avro/internals/mapping):

> Type member names don’t need to match the schema exactly—all non-alphanumeric characters are stripped and comparisons are case-insensitive. So, for example, a record field named `addressLine1` will match type members named `AddressLine1`, `AddressLine_1`, `ADDRESS_LINE_1`, etc.

If you’re able, adding [`DataMember`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.datamemberattribute) attributes to your .NET members would force names to be compared exactly.

> If [`Name`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.datacontractattribute.name) is set, the custom name must match the record field name exactly. If it’s not set, the type member name will be compared inexactly as described above.

**Comment by alanbassi** [comment]
@dstelljes Thanks for your help! Your answer was effective in solving my problem.
