### ISSUE TITLE
Add support for NodaTime

### ISSUE THREAD

**Issue by lillo42** [ch-robinson/dotnet-avro#222]
Hi,

I my project I think about using this project, but in that project I'm using [NodaTime](https://nodatime.org), would be nice if dotnet-avro has support for it.

I think I'll implement it

**Comment by dstelljes** [comment]
To avoid dependency issues, Chr.Avro only supports mapping to types included in .NET. However, it’s certainly possible to use NodaTime with custom cases, and we’d welcome an example as a contribution (similar to [this example](https://github.com/ch-robinson/dotnet-avro/tree/main/examples/Chr.Avro.UnionTypeExample)).
