### ISSUE TITLE
Union with null and multiple selected types throws exception when serializing null.

### ISSUE THREAD

**Issue by darren-clark** [ch-robinson/dotnet-avro#237]
Using a derived BinaryUnionSerializerBuilderCase to override SelectType with specified subclasses, serializing null will fail, throwing "Unexpected type encountered serializing..."

This is due to the check for null being inside each case, which is only executed when Expression.TypeIs returns true, which it will not for null values.

If there is only one case other than null, the serializer works as expected, because there is no type check.

**Comment by dstelljes** [comment]
Thanks for the report and fix, @darren-clark! We’ll release this with 9.3.1 later today.
