### ISSUE TITLE
Usage with confluent-kafka-dotnet's DependentProducerBuilder?

### ISSUE THREAD

**Issue by woodlee** [ch-robinson/dotnet-avro#30]
Hi--thank you for putting this library out there. It looks like it could help us get past several limitations we've encountered with the current Apache/Confluent versions.

The confluent-kafka-dotnet library provides a [DependentProducerBuilder](https://github.com/confluentinc/confluent-kafka-dotnet/blob/v1.2.0/src/Confluent.Kafka/DependentProducerBuilder.cs) which can be used to create additional Avro producers for messages of different types, while still using a single underlying librdkafka handle.

Between this library and the Confluent one, I am not seeing a way to create Avro producers of multiple types that use a single handle. Am I missing anything, or is this something that would require extending your existing `ProducerBuilder` extension methods to cover `DependentProducerBuilder`s as well?

**Comment by dstelljes** [comment]
Yeah, I think adding similar extensions for `DependentProducerBuilder` would be good (pretty sure that the `API-SUBJECT-TO-CHANGE` notice was the reason we didn’t in the past).

The extension methods are pretty thin, so it’s easy to work around if you don’t want to wait for a change:

```csharp
var producer = new DependentProducerBuilder<Null, SomeRecord>(handle)
  .SetValueSerializer(new AsyncSchemaRegistrySerializer<SomeRecord>(...))
  .Build();
```

**Comment by dstelljes** [comment]
Added with #33, will land in 3.0.
