### ISSUE TITLE
Change to ConstructValueSubjectName

### ISSUE THREAD

**Issue by Adnan-cod** [ch-robinson/dotnet-avro#301]
https://github.com/ch-robinson/dotnet-avro/blob/8212f573daf3845a36803128057c275570a4123f/examples/Chr.Avro.UnionTypeExample/Program.cs#L109

**Comment by dstelljes** [comment]
https://github.com/ch-robinson/dotnet-avro/commit/e1d712947c13c132f0da46df307d2e465fd6e3e3
