### ISSUE TITLE
Net8 Support

### ISSUE THREAD

**Issue by jonathan-busuttil** [ch-robinson/dotnet-avro#319]
Are you planning to add Net8 as target framework in these projects? especially the cli

**Comment by dstelljes** [comment]
I see you already marked this as resolved, but just in case anyone else stumbles across this:

* The CLI targets each [supported .NET version](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core). At every major release, we remove versions no longer in support.
* The libraries target netstandard2.0 as a baseline, and net6.0 to support functionality only available in .NET 6 and above (namely `DateOnly` and `TimeOnly`, plus more performant span-based APIs). As .NET 6 goes out of support, we may look at raising that to net8.0 (earliest supported LTS).
