### ISSUE TITLE
Update NuGet icon definition

### ISSUE THREAD

**Issue by dstelljes** [ch-robinson/dotnet-avro#35]
> **iconUrl** is deprecated. Use **icon** instead.

In Chr.Avro.Build.props:

* update PackageIconUrl -> PackageIcon
* include docs/static/nuget-icon.png in the package (like the readme)

**Comment by AmirHMaleki** [comment]
Hey, I want to contribute to open source and it'd be my "first" contribution. So, do you think I can handle it?

**Comment by dstelljes** [comment]
Yeah, absolutely! Once you’ve made the changes, open a PR against the development branch. If you have any questions, drop them here and we’ll try to answer them.

**Comment by AmirHMaleki** [comment]
My first question is that should I only change the Chr.Avro.Build.props file? Or should check the integrity alongside the project?

**Comment by dstelljes** [comment]
That file will be the only thing you need to change. To check that your changes didn't break anything, build the packages:

If you're using Windows:

```
.\build.ps1 -Target Pack
```

If you're using macOS or Linux:

```
./build.sh --target Pack
```

To check that the logo is included in each package, unzip one of the resulting **.nupkg** files in the **releases** folder and make sure that **nuget-icon.png** is in there. If in doubt, just open the PR and we can verify that everything looks good.

**Comment by dstelljes** [comment]
Fixed with #50.
