### ISSUE TITLE
Support constructors for enumerable deserialization

### ISSUE THREAD

**Issue by dstelljes** [ch-robinson/dotnet-avro#42]
Currently, Chr.Avro only supports deserializing lists as arrays or types assignable from `List<T>`. Similarly to #38, we could fall back to a constructor with a single `IEnumerable<T>` parameter (like on [`HashSet<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.hashset-1.-ctor)).

**Comment by Sikta** [comment]
Completed in #48
