### ISSUE TITLE
Schema Registry serdes are incompatible with Confluent.SchemaRegistry 1.4.0

### ISSUE THREAD

**Issue by dstelljes** [ch-robinson/dotnet-avro#85]
`ISchemaRegistryClient.GetLatestSchemaAsync` returns `RegisteredSchema` starting with 1.4.0:

```
Method not found:  System.Threading.Tasks.Task`1<Confluent.SchemaRegistry.Schema> Confluent.SchemaRegistry.ISchemaRegistryClient.GetLatestSchemaAsync(System.String)'.
```

The new lower bound for Chr.Avro.Confluent should be 1.4.0, and since the Confluent clients follow librdkafka versioning, not semver, we should narrow the range of allowed versions (probably to patch instead of minor).

With this change, when fetching a schema, the serdes should check the type to ensure it's Avro.

**Comment by MohamedRDwedar** [comment]
I have this issue also is there sooner fix for this

**Comment by dstelljes** [comment]
@MohamedRDwedar We'll retarget to 1.4.x with the next release. In the meantime, you can downgrade Confluent.SchemaRegistry to 1.3.0.

**Comment by MohamedRDwedar** [comment]
After the downgrade i always got this error in the consumer 

Expression must be writeable (Parameter 'left')
here is my code for the consumer 

using var schemaRegistry = new CachedSchemaRegistryClient(schemaRegistryConfig);
                var serializerBuilder = new SchemaRegistryDeserializerBuilder(schemaRegistry, null, null);
                var consumerBuilder = new ConsumerBuilder<string, TMessage>(consumerConfig);
                var producerBuilderDeserializer = await consumerBuilder.SetAvroValueDeserializer(serializerBuilder, topicName);
                using var builder = producerBuilderDeserializer.SetErrorHandler((_, e) => _logger.LogError(e.Reason))
                                           .SetLogHandler((_, e) => _logger.LogInformation(e.Message))
                                           .Build();
                builder.Subscribe(topicName);
                try
                {
                    while (true)
                    {
                        var consumeResult = builder.Consume();
                        if (consumeResult != null && consumeResult.Message != null)
                        {
                           // Do Something
                        }
                    }
                }

**Comment by dstelljes** [comment]
@MohamedRDwedar That looks like it might be a separate bug. If you open a new issue and include the class you're using for `TMessage`, we can try to help solve it.

**Comment by dstelljes** [comment]
Set to release with 7.0.0.
