### ISSUE TITLE
Support deserializing to System.Collections.ObjectModel collection types

### ISSUE THREAD

**Issue by dstelljes** [ch-robinson/dotnet-avro#97]
Since the library already supports [deserializing to concrete System.Collections.Generic/System.Collections.Immutable types](https://github.com/ch-robinson/dotnet-avro/blob/master/src/Chr.Avro.Binary/BinaryDeserializerBuilder.cs#L482), support for the other .NET Standard collections namespaces makes sense.

**Comment by KaleV-K** [comment]
https://github.com/ch-robinson/dotnet-avro/pull/98

**Comment by dstelljes** [comment]
Released in 8.0.0-rc.0. Opting not to do any types from System.Collections.Specialized at this point since they predate generics.
